Repository wecode-bootcamp-korea/justcode-6-1st-coding-restaurant-front, pull requests merged in 2022-09, with the labels that each got.

#11 은지) [Add]: 마이페이지 탭 기능 구현
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/Mypage.module.scss
  src/styles/reset.scss
Labels: 리뷰요청

#9 지영) [Add]: 회원가입 유효성 검사
  public/image/signUpLogin/apple.png
  public/image/signUpLogin/facebook.png
  public/image/signUpLogin/kakao.png
  public/image/signUpLogin/naver.png
  src/pages/Login/Login.js
  src/pages/Login/Login.module.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.module.scss
Labels: 리팩토링 중

#14 예선) [Design]: root 높이 지정해서 배경색적용 안되는 문제 해결, 헤더 높이설정 해제
  public/data/mainSlide.json
  public/data/orderlistData.json
  public/image/mainSlide/nextIcon.png
  src/components/Header/Header.module.scss
  src/components/MainSlide/MainSlide.js
  src/components/MainSlide/MainSlide.module.scss
  src/index.js
  src/pages/Home/Home.js
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/Orderlist.js
  src/styles/reset.scss
Labels: 리뷰요청

#16 예선) [Fix]: 메인페이지 큰 슬라이더 버그 수정, 최종완성
  public/data/main/mainSlide.json
  src/App.js
  src/components/MainSlide/MainSlide.js
  src/components/MainSlide/MainSlide.module.scss
  src/styles/reset.scss
Labels: 리뷰요청

#17 지영) [Fix]: 회원가입 api - 메시지에 따라 /login 경로설정 및 에러 메시지 나타내기
  src/pages/Signup/Signup.js
Labels: 리뷰요청

#15 지영) [Add]: 로그인 페이지 유효성 검사 및 api 요청
  src/pages/Login/Login.js
Labels: 리뷰요청

#22 찬영)[Refactor]: 카테고리 API 통신 하도록 코드 변경
  src/components/Category/Button.js
  src/components/Category/Button.module.scss
  src/components/Category/Card.js
  src/components/Category/CardList.js
  src/components/Category/CardList.module.scss
  src/components/Category/Title.js
  src/components/Header/MenuMain.js
  src/pages/Category/Category.js
  src/pages/Category/Category.module.scss
Labels: 리뷰요청

#21 예선)[Fix]: 상세페이지 조회 api 완성
  public/data/detail/detail.json
  public/image/sample/bibimbap.jpg
  src/components/Detail/DetailMain.js
  src/components/Detail/DetailMain.module.scss
  src/components/Detail/DetailSub.js
  src/components/Detail/DetailSub.module.scss
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.module.scss
  src/pages/Router.js
Labels: 리뷰요청

#27 예선)[Rename]: 파일경로 수정, 파일/폴더명 컨벤션에 맞게 수정
  public/data/cart/cartList.json
  public/data/category/categoryList.json
  public/data/mainSlide.json
  public/data/myPage/myPage.json
  public/data/myPage/myProfile.json
  public/data/myPage/orderList.json
  public/data/myPage/point.json
  public/data/myPage/review.json
  public/image/main/mainSlide/nextIcon.png
  public/image/sample/bibimbap.jpg
  src/components/Cart/CartItem/CartItem.js
  src/components/Cart/CartItem/CartItem.module.scss
  src/components/Main/MainSlide/MainSlide.js
  src/components/Main/MainSlide/MainSlide.module.scss
  src/components/Mypage/Orderlist.js
  src/components/Mypage/Point.js
  src/components/Mypage/Profile.js
  src/components/Mypage/Review.js
  src/pages/Cart/Cart.js
  src/pages/Category/Category.js
  src/pages/Home/Home.js
  src/pages/Mypage/Mypage.js
Labels: 리뷰요청

#26 찬영)[Fix]: 카테고리 버튼 css 수정
  public/data/category/categoryList.json
  src/components/Cart/CartItem/CartItem.js
  src/components/Category/Button.js
  src/components/Category/Button.module.scss
  src/components/PhotoList/Card.js
  src/components/PhotoList/PhotoList.js
  src/components/PhotoList/PhotoList.module.scss
  src/pages/Cart/Cart.js
Labels: bug

#29 지영) [Delete]: 마이페이지 마이미식- 먹어본 메뉴 삭제
  public/data/myPage/myPage.json
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/Mypage.module.scss
Labels: 리뷰요청

#28 예선)[Fix]: 포인트 api명세 변경으로 목데이터 최종수정
  public/data/myPage/point.json
  src/components/Mypage/Point.js
Labels: 리뷰요청

#31 은지) [Fix]: 마이페이지 내 정보 API추가, 성별 체크박스 수정필요
  public/data/myPage/myProfile.json
  src/components/Mypage/Profile.js
Labels: 코드 수정중

#36 지영) [Add]: Footer UI 구현
  src/components/Footer/Footer.js
  src/components/Footer/Footer.module.scss
  src/pages/Router.js
Labels: 리뷰요청

#34 찬영)[Fix]: 마이페이지 리뷰 컴포넌트 분리 및 리뷰 삭제 기능 구현
  src/components/Category/Card.js
  src/components/Category/CardList.module.scss
  src/components/Mypage/Review.js
  src/components/Mypage/Review.module.scss
  src/components/Mypage/ReviewList.js
Labels: 리뷰요청

#40 예선)[Fix]: 장바구니 get api 목데이터 변경으로 생긴 버그 해결, 총 합계 기능 추가
  src/components/Cart/CartItem/CartItem.js
  src/pages/Cart/Cart.js
Labels: 리뷰요청

#44 예선)[Fix]: 마이페이지 마이미식, 주문내역, 포인트 통신테스트 및 수정
  src/components/Category/CardList.js
  src/components/Detail/DetailSub.js
  src/components/Mypage/Orderlist.js
  src/components/Mypage/Point.js
  src/pages/Cart/Cart.js
  src/pages/Mypage/Mypage.js
Labels: 리뷰요청

#48 예선) [Design]: 각 페이지별 높이 설정 해제
  public/data/cart/cartList.json
  src/pages/Cart/Cart.js
  src/pages/Category/AboutUs.js
  src/pages/Category/Shop.js
  src/pages/Category/Shop.module.scss
  src/pages/Detail/Detail.module.scss
  src/pages/Login/Login.module.scss
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/Mypage.module.scss
  src/pages/Signup/Signup.module.scss
Labels: 리팩토링 중

#55 찬영)[Design]: 로고 버튼 이미지 수정 및 컴포넌트화
  public/image/signUpLogin/apple.png
  public/image/signUpLogin/facebook.png
  public/image/signUpLogin/kakao.png
  public/image/signUpLogin/naver.png
  src/pages/Login/Login.js
  src/pages/Login/Login.module.scss
  src/pages/Login/Logobox.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.module.scss
Labels: 리뷰요청
